In [65]:
import re
from transformers import AutoModelForTokenClassification, AutoTokenizer
import torch
from transformers import BertForTokenClassification, BertTokenizer, BertTokenizerFast
from transformers import pipeline
from tokenizers import decoders

In [66]:
model = BertForTokenClassification.from_pretrained("bert_ner_finetuned_iliad-with-gpu-pattern2.model")

In [67]:
tokenizer = BertTokenizerFast.from_pretrained("bert-base-cased")

In [4]:
label_list = ['O', 'B-CLEntity', 'I-CLEntity', 'L-CLEntity', 'U-CLEntity']

In [5]:
sequence = """The man for wisdom’s various arts renown’d,
Long exercised in woes, O Muse! resound;
Who, when his arms had wrought the destined fall
Of sacred Troy, and razed her heaven-built wall,
Wandering from clime to clime, observant stray’d,
Their manners noted, and their states survey’d,
On stormy seas unnumber’d toils he bore,
Safe with his friends to gain his natal shore:
Vain toils! their impious folly dared to prey
On herds devoted to the god of day;
The god vindictive doom’d them never more
(Ah, men unbless’d!) to touch that natal shore.
Oh, snatch some portion of these acts from fate,
that's Celestial Muse! and to our world relate.
"""

In [70]:
# nlp = pipeline("ner", model=model, tokenizer=tokenizer)

# ner_results = nlp(sequence)
# print(ner_results[:10])

[{'entity': 'LABEL_4', 'score': 0.80995053, 'index': 1, 'word': 'The', 'start': 0, 'end': 3}, {'entity': 'LABEL_0', 'score': 0.9999246, 'index': 2, 'word': 'man', 'start': 4, 'end': 7}, {'entity': 'LABEL_0', 'score': 0.9999582, 'index': 3, 'word': 'for', 'start': 8, 'end': 11}, {'entity': 'LABEL_0', 'score': 0.9999104, 'index': 4, 'word': 'wisdom', 'start': 12, 'end': 18}, {'entity': 'LABEL_0', 'score': 0.99995613, 'index': 5, 'word': '’', 'start': 18, 'end': 19}, {'entity': 'LABEL_0', 'score': 0.999963, 'index': 6, 'word': 's', 'start': 19, 'end': 20}, {'entity': 'LABEL_0', 'score': 0.99996036, 'index': 7, 'word': 'various', 'start': 21, 'end': 28}, {'entity': 'LABEL_0', 'score': 0.99993396, 'index': 8, 'word': 'arts', 'start': 29, 'end': 33}, {'entity': 'LABEL_0', 'score': 0.99997187, 'index': 9, 'word': 're', 'start': 34, 'end': 36}, {'entity': 'LABEL_0', 'score': 0.999957, 'index': 10, 'word': '##no', 'start': 36, 'end': 38}]


In [6]:
tokens = tokenizer.tokenize(tokenizer.decode(tokenizer.encode(sequence)))

In [7]:
tokens[:10]

['[CLS]', 'The', 'man', 'for', 'wisdom', '’', 's', 'various', 'arts', 're']

In [8]:
inputs = tokenizer.encode(sequence, return_tensors="pt")

In [9]:
inputs[0][:10]

tensor([  101,  1109,  1299,  1111, 12304,   787,   188,  1672,  3959,  1231])

In [10]:
outputs = model(inputs).logits

In [11]:
outputs[0][:10]

tensor([[ 8.5953, -2.2641, -2.4301, -1.7081, -2.7219],
        [ 1.7000,  0.4799, -3.5283, -2.5794,  3.4231],
        [ 8.8453, -2.2387, -2.7023, -1.2831, -2.6234],
        [ 9.2018, -2.4289, -2.6260, -1.5701, -3.0763],
        [ 8.5895, -2.0201, -3.0749, -1.6693, -2.1723],
        [ 9.1637, -2.3724, -2.5144, -1.6161, -3.0594],
        [ 9.3578, -2.2696, -2.6097, -1.5840, -3.0662],
        [ 9.2726, -2.4319, -2.6974, -1.5354, -2.9726],
        [ 8.8622, -2.1812, -2.7793, -1.4634, -2.8141],
        [ 9.4867, -2.3407, -2.5629, -1.8648, -3.1766]],
       grad_fn=<SliceBackward>)

In [12]:
predictions = torch.argmax(outputs, dim=2)

In [13]:
predictions[0][:10]

tensor([0, 4, 0, 0, 0, 0, 0, 0, 0, 0])

In [14]:
len(tokens)

185

In [43]:
for token, prediction in zip(tokens, predictions[0].numpy()):
    print((token, model.config.id2label[prediction]))

('[CLS]', 'LABEL_0')
('The', 'LABEL_4')
('man', 'LABEL_0')
('for', 'LABEL_0')
('wisdom', 'LABEL_0')
('’', 'LABEL_0')
('s', 'LABEL_0')
('various', 'LABEL_0')
('arts', 'LABEL_0')
('re', 'LABEL_0')
('##no', 'LABEL_0')
('##wn', 'LABEL_0')
('’', 'LABEL_0')
('d', 'LABEL_0')
(',', 'LABEL_0')
('Long', 'LABEL_4')
('exercised', 'LABEL_0')
('in', 'LABEL_0')
('w', 'LABEL_0')
('##oes', 'LABEL_0')
(',', 'LABEL_0')
('O', 'LABEL_0')
('Muse', 'LABEL_4')
('!', 'LABEL_0')
('re', 'LABEL_0')
('##sound', 'LABEL_0')
(';', 'LABEL_0')
('Who', 'LABEL_4')
(',', 'LABEL_0')
('when', 'LABEL_0')
('his', 'LABEL_0')
('arms', 'LABEL_0')
('had', 'LABEL_0')
('wrought', 'LABEL_0')
('the', 'LABEL_0')
('destined', 'LABEL_0')
('fall', 'LABEL_0')
('Of', 'LABEL_0')
('sacred', 'LABEL_0')
('Troy', 'LABEL_4')
(',', 'LABEL_0')
('and', 'LABEL_0')
('r', 'LABEL_0')
('##azed', 'LABEL_0')
('her', 'LABEL_0')
('heaven', 'LABEL_0')
('-', 'LABEL_0')
('built', 'LABEL_0')
('wall', 'LABEL_0')
(',', 'LABEL_0')
('Wan', 'LABEL_1')
('##dering', '

In [46]:
pred = []
pred_line_label = []
for prediction in predictions[0].numpy():
    pred_line_label.append(label_list[prediction])
pred.append(pred_line_label)
print(pred[0])

['O', 'U-CLEntity', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'U-CLEntity', 'O', 'O', 'O', 'O', 'O', 'O', 'U-CLEntity', 'O', 'O', 'O', 'O', 'U-CLEntity', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'U-CLEntity', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'B-CLEntity', 'L-CLEntity', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'U-CLEntity', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'U-CLEntity', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'U-CLEntity', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'B-CLEntity', 'L-CLEntity', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'U-CLEntity', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'U-CLEntity', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'B-CLEnt

In [17]:
#pattern = r' ([A-Z].[a-z]+)'
pattern = r'(\b[A-Z][a-z]+\b)(\s\b[A-Z][a-z]+\b)*'
re.compile(pattern)

def get_annotations(text, pattern):
    annotations = []
    for match in re.finditer(pattern, text):
        label_dic = dict()
        label_dic['start'] = match.start()
        label_dic['end'] = match.end()
        label_dic['label'] = 'CLEntity' # Entity starting with a capital letter
        annotations.append(label_dic)
    return annotations

In [18]:
ex_annotations = get_annotations(sequence, pattern)

In [19]:
# try an exmaple
from transformers import BertTokenizerFast, BatchEncoding
from tokenizers import Encoding
from alignment import align_tokens_and_annotations_bilou

example = {'content': sequence, 'annotations': ex_annotations}
tokenizer_ex = BertTokenizerFast.from_pretrained('bert-base-cased') # Load a pre-trained tokenizer
tokenized_batch_ex : BatchEncoding = tokenizer_ex(example["content"])
tokenized_text : Encoding = tokenized_batch_ex[0]
labels = align_tokens_and_annotations_bilou(tokenized_text, example["annotations"])


In [20]:
from labelset import LabelSet

ex_label_set = LabelSet(labels=["CLEntity"])
aligned_label_ids = ex_label_set.get_aligned_label_ids_from_annotations(
    tokenized_text, example["annotations"]
)
tokens = tokenized_text.tokens

for token, label in zip(tokens, aligned_label_ids):
    print(token, "-", label)

[CLS] - 0
The - 4
man - 0
for - 0
wisdom - 0
’ - 0
s - 0
various - 0
arts - 0
re - 0
##no - 0
##wn - 0
’ - 0
d - 0
, - 0
Long - 4
exercised - 0
in - 0
w - 0
##oes - 0
, - 0
O - 0
Muse - 4
! - 0
re - 0
##sound - 0
; - 0
Who - 4
, - 0
when - 0
his - 0
arms - 0
had - 0
wrought - 0
the - 0
destined - 0
fall - 0
Of - 4
sacred - 0
Troy - 4
, - 0
and - 0
r - 0
##azed - 0
her - 0
heaven - 0
- - 0
built - 0
wall - 0
, - 0
Wan - 1
##dering - 3
from - 0
c - 0
##lim - 0
##e - 0
to - 0
c - 0
##lim - 0
##e - 0
, - 0
o - 0
##bs - 0
##er - 0
##vant - 0
stray - 0
’ - 0
d - 0
, - 0
Their - 4
manners - 0
noted - 0
, - 0
and - 0
their - 0
states - 0
survey - 0
’ - 0
d - 0
, - 0
On - 4
storm - 0
##y - 0
seas - 0
un - 0
##num - 0
##ber - 0
’ - 0
d - 0
to - 0
##ils - 0
he - 0
bore - 0
, - 0
Safe - 4
with - 0
his - 0
friends - 0
to - 0
gain - 0
his - 0
na - 0
##tal - 0
shore - 0
: - 0
V - 1
##ain - 3
to - 0
##ils - 0
! - 0
their - 0
imp - 0
##ious - 0
f - 0
##olly - 0
dared - 0
to - 0
prey - 0
On - 4
herd - 0

In [47]:
true = []
true_line_label = []
for label in aligned_label_ids:
    true_line_label.append(label_list[label])
true.append(true_line_label)
print(true[0][:10])

['O', 'U-CLEntity', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O']


In [52]:
from seqeval.metrics import accuracy_score, f1_score, classification_report, precision_score, recall_score
from seqeval.scheme import BILOU

print(classification_report(true, pred, mode='strict', scheme=BILOU))

              precision    recall  f1-score   support

    CLEntity       0.92      0.75      0.83        16

   micro avg       0.92      0.75      0.83        16
   macro avg       0.92      0.75      0.83        16
weighted avg       0.92      0.75      0.83        16



In [64]:
# recall = recall_score(true, pred)
# precision_score(true, pred)
# from matplotlib import pyplot
# # plot the model precision-recall curve
# pyplot.plot(recall, precision, marker='.')
# # axis labels
# pyplot.xlabel('Recall')
# pyplot.ylabel('Precision')
# # show the legend
# pyplot.legend()
# # show the plot
# pyplot.show()

In [ ]:
## https://huggingface.co/docs/tokenizers/python/latest/pipeline.html
# tokenizer.decoder = decoders.WordPiece()
# tokenizer.decode(outputs.ids)

In [ ]:
odyssey_lines = []
book = open("../example-texts/odyssey.txt")
for line in book:
    line = line.strip()
    odyssey_lines.append(line)

In [ ]:
odyssey_lines = [line for line in odyssey_lines if line]

In [ ]:
odyssey_lines[:10]

In [ ]:
## https://huggingface.co/docs/tokenizers/python/latest/pipeline.html
# tokenizer.decoder = decoders.WordPiece()
# tokenizer.decode(outputs.ids)

In [ ]:
for line in odyssey_lines:
    tokens_line = tokenizer.tokenize(tokenizer.decode(tokenizer.encode(line)))
    inputs_line = tokenizer.encode(line, return_tensors="pt")

    outputs_line = model(inputs_line).logits
    predictions_line = torch.argmax(outputs_line, dim=2)

In [ ]:
json_data = []
book = open("../example-texts/odyssey.txt")
for line in book:
    line = line.strip()
    
    line_data = dict()
    line_data['content'] = line
    line_data['annotations'] = get_annotations(line, pattern)
    json_data.append(line_data)

In [ ]:
# For testing the result. Need a way to test whether tuned bert is accurately identifying CLEntities
json_data[:10] 

In [ ]:
from transformers import BertTokenizerFast
